# Generated by Django 3.1.7 on 2021-07-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_det',
            name='sessby',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Mentor'), (3, 'Collaborator'), (4, 'Admin')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session_det',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
