# Generated by Django 3.2.5 on 2021-07-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20210711_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_det',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
